call biochain.bat -inputfilefull data\input\0002\0002-ArticleSummary_Saya-Model.spl -outputtype conceptcount -outputfile data\output\0002\0002-ConceptCount_Saya.txt
call biochain.bat -inputfilefull data\input\0013\0013-ArticleSummary_Saya-Model.spl -outputtype conceptcount -outputfile data\output\0013\0013-ConceptCount_Saya.txt
call biochain.bat -inputfilefull data\input\0162\0162-ArticleSummary_Saya-Model.spl -outputtype conceptcount -outputfile data\output\0162\0162-ConceptCount_Saya.txt
call biochain.bat -inputfilefull data\input\0234\0234-ArticleSummary_Saya-Model.spl -outputtype conceptcount -outputfile data\output\0234\0234-ConceptCount_Saya.txt
call biochain.bat -inputfilefull data\input\0782\0782-ArticleSummary_Saya-Model.spl -outputtype conceptcount -outputfile data\output\0782\0782-ConceptCount_Saya.txt
call biochain.bat -inputfilefull data\input\0786\0786-ArticleSummary_Saya-Model.spl -outputtype conceptcount -outputfile data\output\0786\0786-ConceptCount_Saya.txt
call biochain.bat -inputfilefull data\input\0787\0787-ArticleSummary_Saya-Model.spl -outputtype conceptcount -outputfile data\output\0787\0787-ConceptCount_Saya.txt
call biochain.bat -inputfilefull data\input\0811\0811-ArticleSummary_Saya-Model.spl -outputtype conceptcount -outputfile data\output\0811\0811-ConceptCount_Saya.txt
call biochain.bat -inputfilefull data\input\0814\0814-ArticleSummary_Saya-Model.spl -outputtype conceptcount -outputfile data\output\0814\0814-ConceptCount_Saya.txt
call biochain.bat -inputfilefull data\input\0821\0821-ArticleSummary_Saya-Model.spl -outputtype conceptcount -outputfile data\output\0821\0821-ConceptCount_Saya.txt
call biochain.bat -inputfilefull data\input\0954\0954-ArticleSummary_Saya-Model.spl -outputtype conceptcount -outputfile data\output\0954\0954-ConceptCount_Saya.txt
call biochain.bat -inputfilefull data\input\1001\1001-ArticleSummary_Saya-Model.spl -outputtype conceptcount -outputfile data\output\1001\1001-ConceptCount_Saya.txt
call biochain.bat -inputfilefull data\input\1108\1108-ArticleSummary_Saya-Model.spl -outputtype conceptcount -outputfile data\output\1108\1108-ConceptCount_Saya.txt
call biochain.bat -inputfilefull data\input\1110\1110-ArticleSummary_Saya-Model.spl -outputtype conceptcount -outputfile data\output\1110\1110-ConceptCount_Saya.txt
call biochain.bat -inputfilefull data\input\1111\1111-ArticleSummary_Saya-Model.spl -outputtype conceptcount -outputfile data\output\1111\1111-ConceptCount_Saya.txt
call biochain.bat -inputfilefull data\input\1115\1115-ArticleSummary_Saya-Model.spl -outputtype conceptcount -outputfile data\output\1115\1115-ConceptCount_Saya.txt
call biochain.bat -inputfilefull data\input\1117\1117-ArticleSummary_Saya-Model.spl -outputtype conceptcount -outputfile data\output\1117\1117-ConceptCount_Saya.txt
call biochain.bat -inputfilefull data\input\1118\1118-ArticleSummary_Saya-Model.spl -outputtype conceptcount -outputfile data\output\1118\1118-ConceptCount_Saya.txt
call biochain.bat -inputfilefull data\input\1122\1122-ArticleSummary_Saya-Model.spl -outputtype conceptcount -outputfile data\output\1122\1122-ConceptCount_Saya.txt
call biochain.bat -inputfilefull data\input\1132\1132-ArticleSummary_Saya-Model.spl -outputtype conceptcount -outputfile data\output\1132\1132-ConceptCount_Saya.txt
call biochain.bat -inputfilefull data\input\1197\1197-ArticleSummary_Saya-Model.spl -outputtype conceptcount -outputfile data\output\1197\1197-ConceptCount_Saya.txt
call biochain.bat -inputfilefull data\input\3563\3563-ArticleSummary_Saya-Model.spl -outputtype conceptcount -outputfile data\output\3563\3563-ConceptCount_Saya.txt
call biochain.bat -inputfilefull data\input\4016\4016-ArticleSummary_Saya-Model.spl -outputtype conceptcount -outputfile data\output\4016\4016-ConceptCount_Saya.txt
call biochain.bat -inputfilefull data\input\4017\4017-ArticleSummary_Saya-Model.spl -outputtype conceptcount -outputfile data\output\4017\4017-ConceptCount_Saya.txt
