@echo off
call ..\biosumm.bat -inputfilefull %DATA_HOME%\summarization\input\0002\0002-Article-A.txt -outputtype phrases -outputfile %DATA_HOME%\summarization\output\0002\0002-ArticlePhrases_mmtx.txt
call ..\biosumm.bat -inputfilefull %DATA_HOME%\summarization\input\0013\0013-Article-A.txt -outputtype phrases -outputfile %DATA_HOME%\summarization\output\0013\0013-ArticlePhrases_mmtx.txt
call ..\biosumm.bat -inputfilefull %DATA_HOME%\summarization\input\0162\0162-Article-A.txt -outputtype phrases -outputfile %DATA_HOME%\summarization\output\0162\0162-ArticlePhrases_mmtx.txt
call ..\biosumm.bat -inputfilefull %DATA_HOME%\summarization\input\0234\0234-Article-A.txt -outputtype phrases -outputfile %DATA_HOME%\summarization\output\0234\0234-ArticlePhrases_mmtx.txt
call ..\biosumm.bat -inputfilefull %DATA_HOME%\summarization\input\0782\0782-Article-A.txt -outputtype phrases -outputfile %DATA_HOME%\summarization\output\0782\0782-ArticlePhrases_mmtx.txt
call ..\biosumm.bat -inputfilefull %DATA_HOME%\summarization\input\0786\0786-Article-A.txt -outputtype phrases -outputfile %DATA_HOME%\summarization\output\0786\0786-ArticlePhrases_mmtx.txt
call ..\biosumm.bat -inputfilefull %DATA_HOME%\summarization\input\0787\0787-Article-A.txt -outputtype phrases -outputfile %DATA_HOME%\summarization\output\0787\0787-ArticlePhrases_mmtx.txt
call ..\biosumm.bat -inputfilefull %DATA_HOME%\summarization\input\0811\0811-Article-A.txt -outputtype phrases -outputfile %DATA_HOME%\summarization\output\0811\0811-ArticlePhrases_mmtx.txt
call ..\biosumm.bat -inputfilefull %DATA_HOME%\summarization\input\0814\0814-Article-A.txt -outputtype phrases -outputfile %DATA_HOME%\summarization\output\0814\0814-ArticlePhrases_mmtx.txt
call ..\biosumm.bat -inputfilefull %DATA_HOME%\summarization\input\0821\0821-Article-A.txt -outputtype phrases -outputfile %DATA_HOME%\summarization\output\0821\0821-ArticlePhrases_mmtx.txt
call ..\biosumm.bat -inputfilefull %DATA_HOME%\summarization\input\0954\0954-Article-A.txt -outputtype phrases -outputfile %DATA_HOME%\summarization\output\0954\0954-ArticlePhrases_mmtx.txt
call ..\biosumm.bat -inputfilefull %DATA_HOME%\summarization\input\1001\1001-Article-A.txt -outputtype phrases -outputfile %DATA_HOME%\summarization\output\1001\1001-ArticlePhrases_mmtx.txt
call ..\biosumm.bat -inputfilefull %DATA_HOME%\summarization\input\1108\1108-Article-A.txt -outputtype phrases -outputfile %DATA_HOME%\summarization\output\1108\1108-ArticlePhrases_mmtx.txt
call ..\biosumm.bat -inputfilefull %DATA_HOME%\summarization\input\1110\1110-Article-A.txt -outputtype phrases -outputfile %DATA_HOME%\summarization\output\1110\1110-ArticlePhrases_mmtx.txt
call ..\biosumm.bat -inputfilefull %DATA_HOME%\summarization\input\1111\1111-Article-A.txt -outputtype phrases -outputfile %DATA_HOME%\summarization\output\1111\1111-ArticlePhrases_mmtx.txt
call ..\biosumm.bat -inputfilefull %DATA_HOME%\summarization\input\1115\1115-Article-A.txt -outputtype phrases -outputfile %DATA_HOME%\summarization\output\1115\1115-ArticlePhrases_mmtx.txt
call ..\biosumm.bat -inputfilefull %DATA_HOME%\summarization\input\1117\1117-Article-A.txt -outputtype phrases -outputfile %DATA_HOME%\summarization\output\1117\1117-ArticlePhrases_mmtx.txt
call ..\biosumm.bat -inputfilefull %DATA_HOME%\summarization\input\1118\1118-Article-A.txt -outputtype phrases -outputfile %DATA_HOME%\summarization\output\1118\1118-ArticlePhrases_mmtx.txt
call ..\biosumm.bat -inputfilefull %DATA_HOME%\summarization\input\1122\1122-Article-A.txt -outputtype phrases -outputfile %DATA_HOME%\summarization\output\1122\1122-ArticlePhrases_mmtx.txt
call ..\biosumm.bat -inputfilefull %DATA_HOME%\summarization\input\1132\1132-Article-A.txt -outputtype phrases -outputfile %DATA_HOME%\summarization\output\1132\1132-ArticlePhrases_mmtx.txt
call ..\biosumm.bat -inputfilefull %DATA_HOME%\summarization\input\1197\1197-Article-A.txt -outputtype phrases -outputfile %DATA_HOME%\summarization\output\1197\1197-ArticlePhrases_mmtx.txt
call ..\biosumm.bat -inputfilefull %DATA_HOME%\summarization\input\3563\3563-Article-A.txt -outputtype phrases -outputfile %DATA_HOME%\summarization\output\3563\3563-ArticlePhrases_mmtx.txt
call ..\biosumm.bat -inputfilefull %DATA_HOME%\summarization\input\4016\4016-Article-A.txt -outputtype phrases -outputfile %DATA_HOME%\summarization\output\4016\4016-ArticlePhrases_mmtx.txt
call ..\biosumm.bat -inputfilefull %DATA_HOME%\summarization\input\4017\4017-Article-A.txt -outputtype phrases -outputfile %DATA_HOME%\summarization\output\4017\4017-ArticlePhrases_mmtx.txt
